language: objective-c
xcode_workspace: Spectacle.xcworkspace
xcode_scheme: Spectacle

before_install:
  - gem install cocoapods -v '0.34.4'

before_script:
  - export LANG=en_US.UTF-8

script:
  - xctool -workspace Spectacle.xcworkspace -scheme Spectacle test
